version: '3'

services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: releven
      POSTGRES_USER: releven
      POSTGRES_PASSWORD: releven
    volumes:
      - "db:/var/lib/postgresql/data/"
volumes:
  db:

