"""autodatetime

Revision ID: 6912a5e6a655
Revises: d96cf01df428
Create Date: 2022-11-20 17:02:29.772412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6912a5e6a655'
down_revision = 'd96cf01df428'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
