"""autodatetime

Revision ID: a867d9776fc5
Revises: 6912a5e6a655
Create Date: 2022-11-20 17:15:16.554596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a867d9776fc5'
down_revision = '6912a5e6a655'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
